### ISSUE TITLE
Unable to start the project

### ISSUE THREAD

**Issue by Semer7** [divijan/fsm-test-assignment#1]
Hi,

I'm reviewing your project and it seems neat at first glance. But I'm not able to build it because of unresolved guice dependency in build.sbt. Maybe your Dependencies.scala is not pushed or maybe this guice dependency is imported via some other mechanism but your project doesn't compile out of the box. Feel free to reach out to me to fix this issue.

**Comment by divijan** [comment]
Fixed in v1.0.1. It was an issue with .gitignore: it ignored the whole `project/` directory with `plugins.sbt` and `build.properties`
