### ISSUE TITLE
comparison with e.getMessage

### ISSUE THREAD

**Issue by rssh** [divijan/fsm-test-assignment#7]
https://github.com/divijan/fsm-test-assignment/blob/5056d61bd185f0a9b919d02f5e37efa013567fd5/app/controllers/Entities.scala#L69

1.  You can't prove, that exists only one reason, that  'Action.witFilter failed'.  If puter reason exists, person who will debug you program, will be in trable.
2.  Messages are subjects for cosmetics changes or localization.  Nobody will expect, that changing message will break something in the other parts of the code.  Consider using codes or except types of exception

**Comment by divijan** [comment]
Fixed in https://github.com/divijan/fsm-test-assignment/commit/f8bf540828a90e5f0a86c3c62b856ea17b1c1066
