### ISSUE TITLE
Future( short operation )  instead Future successfull 

### ISSUE THREAD

**Issue by rssh** [divijan/fsm-test-assignment#8]
https://github.com/divijan/fsm-test-assignment/blob/5056d61bd185f0a9b919d02f5e37efa013567fd5/app/controllers/Entities.scala#L43

Are you sure, that request.body.as[EntityName] should be run in other task ?  Maybe you want Future successful here ?

**Comment by divijan** [comment]
If code inside Future.successful throws, exception leaks out of the Future scope. This way I get a failed Future in case deserialization fails which I can compose with DB access Future
